version: '3.1'
services:

  redis:
    image: 'redis:6.2'
    networks:
      - hmpps
    container_name: redis-micro-frontends
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth-micro-frontends
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0

  nginx:
    image: nginxinc/nginx-unprivileged:1.23.3
    depends_on: [app]
    networks:
      - hmpps
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf

  app:
    build: .
    networks:
      - hmpps
    depends_on: [redis]
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - HMPPS_AUTH_EXTERNAL_URL=http://localhost:9090/auth
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - PORT=3000
      - NODE_ENV=development
      - API_CLIENT_ID=hmpps-prisoner-profile
      - API_CLIENT_SECRET=clientsecret
      - SYSTEM_CLIENT_ID=hmpps-prisoner-profile-system
      - SYSTEM_CLIENT_SECRET=clientsecret
      - SESSION_SECRET=session-secret
      - DPS_HOME_PAGE_URL=http://localhost:3000

networks:
  hmpps:
