version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@7
  slack: circleci/slack@4.12.1

parameters:
  node-version:
    type: string
    default: 18.12-browsers

jobs:
  build:
    executor:
      name: hmpps/node
      tag: << pipeline.parameters.node-version >>
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci --no-audit
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - ~/.cache
      - run:
          command: |
            npm run build
            DATE=$(date '+%Y-%m-%d')
            export BUILD_NUMBER=${DATE}.${CIRCLE_BUILD_NUM}
            export GIT_REF="$CIRCLE_SHA1"
            npm run record-build-info
      - run:
          name: Linter check
          command: npm run lint
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - build-info.json
            - build
            - dist

  unit_test:
    executor:
      name: hmpps/node
      tag: << pipeline.parameters.node-version >>
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: unit tests
          command: npm run test:ci
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results/unit-test-reports.html

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - app/build:
          working_directory: ./app/
          filters:
            tags:
              ignore: /.*/
      - app/unit_test:
          working_directory: ./app/
          requires:
            - app/build
      # Dont deploy these at the moment
      # - app/hmpps/helm_lint:
      #     name: helm_lint
      # - app/hmpps/build_docker:
      #     name: build_docker
      #     filters:
      #       branches:
      #         only:
      #           - main
      # - app/hmpps/deploy_env:
      #     name: app/deploy_dev
      #     env: "dev"
      #     jira_update: true
      #     context: hmpps-common-vars
      #     filters:
      #       branches:
      #         only:
      #           - main
      #     requires:
      #       - app/helm_lint
      #       - app/unit_test
      #       - app/build_docker
      #     helm_timeout: 5m
      - components/build:
          working_directory: ./components/
          filters:
            tags:
              ignore: /.*/
      - components/unit_test:
          working_directory: ./components/
          requires:
            - build
      # Dont deploy these at the moment
      # - components/hmpps/helm_lint:
      #     name: helm_lint
      # - components/hmpps/build_docker:
      #     name: build_docker
      #     filters:
      #       branches:
      #         only:
      #           - main
      # - components/hmpps/deploy_env:
      #     name: deploy_dev
      #     env: "dev"
      #     jira_update: true
      #     context: hmpps-common-vars
      #     filters:
      #       branches:
      #         only:
      #           - main
      #     requires:
      #       - components/helm_lint
      #       - components/unit_test
      #       - components/build_docker
      #     helm_timeout: 5m
