---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-main
data:
  nginx.conf: |
    pid /tmp/nginx.pid;
    worker_processes  auto;
    events {
      worker_connections  1024;
    }
    http {
      keepalive_timeout  65;
      gzip  on;
      server {
        listen       8080;
        server_name  localhost;
        ssi on;
        ssi_silent_errors off;
        proxy_set_header Accept-Encoding "";
        proxy_intercept_errors on;
        proxy_ssl_server_name on;

        location / {
          proxy_pass http://hmpps-micro-frontend-poc.hmpps-micro-frontend-poc-dev.svc.cluster.local/;
        }
    
        location /component{
          proxy_pass http://hmpps-micro-frontend-poc-component.hmpps-micro-frontend-poc-dev.svc.cluster.local/;
        }
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: hmpps-micro-frontend-poc-nginx
    app.kubernetes.io/name: hmpps-micro-frontend-poc-nginx
  name: hmpps-micro-frontend-poc-nginx
  namespace: hmpps-micro-frontend-poc-dev
spec:
  containers:
    - name: common
      image: nginxinc/nginx-unprivileged:1.23.3
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-main
        items:
          - key: nginx.conf
            path: nginx.conf
  restartPolicy: Never
