---
# Per environment values which override defaults in hmpps-micro-frontend-poc/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    enabled: true
    host: micro-frontend-poc-dev.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-micro-frontend-poc-cert
    annotations:
      nginx.ingress.kubernetes.io/custom-http-errors: "418" 
      nginx.ingress.kubernetes.io/server-snippet: |
        ssi on;
        ssi_silent_errors off;
        location ~ /component/(prisoner/.*) {
          proxy_pass https://micro-frontend-poc-component-dev.hmpps.service.justice.gov.uk/$1;
          #proxy_pass http://172.20.112.189:8080/$1;
        }
        location ~ /(component/assets/.*) {
          proxy_pass https://micro-frontend-poc-component-dev.hmpps.service.justice.gov.uk/$1;
        }

  env:
    INGRESS_URL: "https://micro-frontend-poc-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    DPS_HOME_PAGE_URL: "https://digital-dev.prison.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

