---
# Per environment values which override defaults in hmpps-micro-frontend-poc/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: micro-frontend-poc-dev.hmpps.service.justice.gov.uk
    contextColour: green
    v1_2_enabled: true
    v0_47_enabled: false
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        ssi on;
        ssi_silent_errors off;
        gzip on;
        gunzip on;
        location ~ /(component/assets/.*) {
          proxy_pass https://hmpps-micro-frontend-components-dev.hmpps.service.justice.gov.uk/$1$is_args$args;
          proxy_set_header Host hmpps-micro-frontend-components-dev.hmpps.service.justice.gov.uk;
        }
        location ~ /component/(.*) {
          proxy_pass https://hmpps-micro-frontend-components-dev.hmpps.service.justice.gov.uk/$1$is_args$args;
          proxy_set_header Host hmpps-micro-frontend-components-dev.hmpps.service.justice.gov.uk;
        }
  env:
    INGRESS_URL: "https://micro-frontend-poc-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    SESSION_API_URL: "https://central-session-api-dev.hmpps.service.justice.gov.uk"
    COMPONENT_API_URL: "https://hmpps-micro-frontend-components-dev.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

